# Generated by Django 5.0.6 on 2024-07-03 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(choices=[('SAPIN BLANC 3m', 'SAPIN BLANC 3m'), ('SAPIN BLANC 4m', 'SAPIN BLANC 4m'), ('DOUKA 2.90 POUTRE H20', 'DOUKA 2.90 POUTRE H20'), ('DOUKA 3.90 POUTRE H20', 'DOUKA 3.90 POUTRE H20'), ('KAUFMANN 80 X 2900', 'KAUFMANN 80 X 2900'), ('KAUFMANN 80 X 3900', 'KAUFMANN 80 X 3900'), ('ECHAFFAUDAGE 1m', 'ECHAFFAUDAGE 1m'), ('ECHAFFAUDAGE 70cm', 'ECHAFFAUDAGE 70cm')], max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('unite_mesure', models.CharField(max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_bon_commande', models.CharField(blank=True, max_length=50, null=True)),
                ('num_bon_livraison', models.CharField(blank=True, max_length=50, null=True)),
                ('fournisseur', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionM.chantier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
